import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';

const Home: NextPage = () => {
	const router = useRouter();
	const [letters, setLetters] = useState('');

	const handleSubmit = () => {
		router.push(`/${letters.toLowerCase()}`);
	};

	return (
		<div>
			<Head>
				<title>Spelling Bee Solver</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex h-screen flex-col items-center gap-5 bg-[#F2DB50] px-10 pt-[5%] text-center text-black">
				<img src="/spellingbee.png" alt="bee" className="w-24" />
				<div className="text-4xl font-bold">SUCK at the NYT Spelling Bee?</div>
				<div>
					Well, I can help you needlessly impress your family members with your sick score, bro
				</div>
				<div>Enter the letters for the puzzle, STARTING with the center letter</div>
				<input
					className="rounded-lg bg-white py-2 px-6 focus:outline-none"
					value={letters}
					onChange={(e) => setLetters(e.target.value)}
				></input>
				<button
					className="rounded-full bg-black px-6 py-2 font-semibold text-white"
					onClick={handleSubmit}
				>
					🔥 SOLVE 🔥
				</button>
				<div className="text-sm font-light text-gray-500">
					NOTE: I am not liable for damages when people realize you are a filthy cheater
				</div>
			</div>
		</div>
	);
};

export default Home;
